### PR TITLE
Feat/match base quad pattern

### PR DESCRIPTION
**Pull request by jeswr**
Made this for the reasoning components I am working on and figured that this belonged upstream :)

### CODE REVIEW

**Comment by rubensworks** [comment]
I may be missing something after glancing over this, but is there any difference with the already-existing `matchPatternComplete`?

**Comment by jeswr** [comment]
If you consider the pattern `?s a ?s` and the triple `Jesse a Thing`; then matchPatternComplete will return true, but we actually want this to return false since `Jesse` and `Thing` are not the same.

On the other hand we want `?s a ?s` and `Jesse a Jesse` to match.

The use case is to help [skip reasoning on patterns that have already been reasoned against](https://github.com/comunica/comunica-feature-reasoning/blob/d61baef90542cfe7dc7c72005209d03e6705064d/packages/bus-rdf-reason/lib/ActorRdfReasonMediated.ts#L87-L107)

**Comment by rubensworks** [comment]
Ah ok, that makes sense.

It's just the terminology that I trip over then, I thought it had something to do with BaseQuad versus normal Quad.
Perhaps the name could becoe `matchPatternMappings` or `matchPatternBindings`?
Or perhaps `matchPattern` and `matchPatternComplete` could gain an optional options object in which you can set `mappings` to `true` to enable mappings-matching?

**Comment by jeswr** [comment]
@rubensworks resolved

**Comment by rubensworks** [comment]
Thanks! Released as 1.8.0. (note that I reversed the arg order to be aligned with the other methods)

**Pull request merged**
